export const LECTURE_LOADING = "LECTURE_LOADING";
export const GET_LECTURE_SUCCESS = "GET_LECTURE_SUCCESS";
export const LECTURE_ERROR = "LECTURE_ERROR";
export const EDIT_LECTURE_SUCCESS = "EDIT_LECTURE_SUCCESS";
export const DELETE_LECTURE_SUCCESS = "DELETE_LECTURE_SUCCESS";
export const ADD_LECTURE_SUCCESS = "ADD_LECTURE_SUCCESS";
