export const COURSE_LOADING = "COURSE_LOADING";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const COURSE_ERROR = "COURSE_ERROR";
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
